version: "3.3"  # optional since v1.27.0

services:
  text-generation-webui:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8889:8889"
    stdin_open: true
    tty: true
    volumes:
      - ./models:/app/models
      - ./characters:/app/characters
      - ./softprompts:/app/softprompts
      - build-cache:/app/repositories/GPTQ-for-LLaMa/build
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]

volumes:
  build-cache: